### ISSUE TITLE
SAMPLES_DIR is missing at gulpfile.js

### ISSUE THREAD

**Issue by juliantoledo** [ampproject/amp-by-example#64]
[21:40:56] 'compile:sitemap' errored after 186 μs
[21:40:56] ReferenceError: SAMPLES_DIR is not defined
    at Gulp.<anonymous> (/Users/jtoledo/Documents/workspace/amp-by-example/gulpfile.js:167:19)
    at module.exports (/Users/jtoledo/Documents/workspace/amp-by-example/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/jtoledo/Documents/workspace/amp-by-example/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/jtoledo/Documents/workspace/amp-by-example/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/jtoledo/Documents/workspace/amp-by-example/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:139:18)

**Comment by kul3r4** [comment]
This is fixed here: https://github.com/ampproject/amp-by-example/pull/45

**Comment by juliantoledo** [comment]
great!

**Comment by kul3r4** [comment]
This has been solved.
